name: 'Reqover'
description: 'Publish reqover results'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  filePath:
    description: 'Coverage json file path'
    required: false
    default: './coverage.json'
  githubToken:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
