name: 'Reqover'
description: 'Publish reqover results'
inputs:
  serverUrl:
    description: 'Reqover server url'
    required: false
    default: 'https://reqover-io.herokuapp.com'
  projectToken:
    description: 'Reqover project token'
    required: true
  buildName:
    description: 'Reqover build name for target project'
    required: true
  githubToken:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
runs:
  using: 'node16'
  main: 'index.js'